# Generated by Django 4.2.2 on 2024-06-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_number_order_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
    ]
